const data = {
    products:[
        {
            _id: '1',
            name: 'Slim Fit Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock: 10,
            brand:'Local',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Slim Fit Shirt Female',
            category:'Shirts',
            image:'/images/p2.jpg',
            price:100,
            countInStock: 20,
            brand:'Local',
            rating:4.8,
            numReviews:50,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Slim Fit pants',
            category:'Pants',
            image:'/images/p3.jpg',
            price:120,
            countInStock: 0,
            brand:'Local',
            rating:3.5,
            numReviews:20,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Slim Fit Shirt',
            category:'Shirts',
            image:'/images/p4.jpg',
            price:120,
            countInStock: 15,
            brand:'Local',
            rating:4.5,
            numReviews:45,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Slim Fit Shirt',
            category:'Shirts',
            image:'/images/p5.jpg',
            price:125,
            countInStock: 5,
            brand:'Local',
            rating:4.5,
            numReviews:14,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Slim Fit Shirt',
            category:'Shirts',
            image:'/images/p6.jpg',
            price:120,
            countInStock: 12,
            brand:'Local',
            rating:4.5,
            numReviews:100,
            description: 'high quality product',
        },
        
    ],
};
export default data;